// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQ2d0yTkTwVBiEwUc1UDTNOQMd61yH7I',
    appId: '1:584092717629:web:bd8ba365893bdd43b59054',
    messagingSenderId: '584092717629',
    projectId: 'chatsjournal',
    authDomain: 'chatsjournal.firebaseapp.com',
    databaseURL: 'https://chatsjournal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatsjournal.appspot.com',
    measurementId: 'G-YRXW3MVS2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRS2lkrcOxQ6NYJwOaoXeICjCHPcJSjHw',
    appId: '1:584092717629:android:c576f9affb6e33d0b59054',
    messagingSenderId: '584092717629',
    projectId: 'chatsjournal',
    databaseURL: 'https://chatsjournal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatsjournal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5LAxBlgJx8Ghh4XfScuih4i8AlIv4bQg',
    appId: '1:584092717629:ios:2d8c399337aa0182b59054',
    messagingSenderId: '584092717629',
    projectId: 'chatsjournal',
    databaseURL: 'https://chatsjournal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatsjournal.appspot.com',
    iosClientId: '584092717629-m1cgcjtqm8trpcml7ltsqd4phr62lgbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
