name: diary
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0+3
  path: ^1.8.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  hashtagable: ^2.1.0
  share_plus: ^6.3.0
  animations: ^2.0.7
  rive: ^0.10.1
  bloc_test: ^9.1.0
  mockito: ^5.3.2
  mocktail: ^0.3.0
  syncfusion_flutter_charts: ^20.4.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/

