// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGzReqI58mmfmczUHAj9bmoSijbCQ3xc',
    appId: '1:1026621417851:android:dafcdd66c6cad8605575de',
    messagingSenderId: '1026621417851',
    projectId: 'my-journal-b0160',
    databaseURL: 'https://my-journal-b0160-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-journal-b0160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJfR8THiQV4a0eTfUTD1Be9h8czzCLOs',
    appId: '1:1026621417851:ios:2e20c58af1b3d7f45575de',
    messagingSenderId: '1026621417851',
    projectId: 'my-journal-b0160',
    databaseURL: 'https://my-journal-b0160-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-journal-b0160.appspot.com',
    iosClientId: '1026621417851-j0f254t12ishiktreh4bva0uqmou0q6s.apps.googleusercontent.com',
    iosBundleId: 'com.temaandone.myjournal',
  );
}
