// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1sOCU5jv3cLL_X86dYll4uxtO3f1FQg',
    appId: '1:1084681149400:android:fc65f9654bae02ef9c70ad',
    messagingSenderId: '1084681149400',
    projectId: 'chatjournal-7ac64',
    databaseURL: 'https://chatjournal-7ac64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatjournal-7ac64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzML9VgtKTpDGvsIN2nRmANucXtEZdaG8',
    appId: '1:1084681149400:ios:26e347308503100d9c70ad',
    messagingSenderId: '1084681149400',
    projectId: 'chatjournal-7ac64',
    databaseURL: 'https://chatjournal-7ac64-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatjournal-7ac64.appspot.com',
    iosClientId: '1084681149400-c7he7tlebr44iq0mohka56hgl2ec854c.apps.googleusercontent.com',
    iosBundleId: 'com.lizaveta16.chatJournal',
  );
}
